admittance_control:
  propotional_gain_pose_x: 0.1
  propotional_gain_pose_y: 0.1
  propotional_gain_pose_z: 0.1
  propotional_gain_pose_roll: 0.1
  propotional_gain_pose_pitch: 0.1
  propotional_gain_pose_yaw: 0.1