VoronoiGlobalPlanner:
  free_cell_threshold: 0
  angle_threshold: 0.0 # 0.3927 # PI / 8; 22,5°
  min_distance_control_points: 1.25
  max_distance_for_interpolation: 1.0
  plan_resolution: 50 # pt / m
  max_curvature: 10.0
  curvature_safety_margin: 0.02
  min_facet_area: 10.0
  use_as_standalone: true
  optimize_lengths: true
  max_optimization_time: 4.0

  formation_config:
    robot_names: ["/mir1", "/mir2"]
    mir1:
      namespace: /mir1
      rel_x_offset: 0.0
      rel_y_offset: 0.01
      rel_yaw_offset: 0.0
    mir2:
      namespace: /mir2
      rel_x_offset: 0.0
      rel_y_offset: -0.01
      rel_yaw_offset: 0.0