# Add the static theta value to the current joint_state. 
# The active joint is not specified esplicitly
# Angles are in ° because it is easier to convert to rad later (no long decimal numbers)
dh_params:
  joint1:
    theta: 0.0
    a: 0.0
    d: 0.1807
    alpa: 90
  joint2:
    theta: q_2
    a: -0.6127
    d: 0.0
    alpa: 0.0
  joint3:
    theta: q_3
    a: -0.57155
    d: 0.0
    alpa: 0.0
  joint4:
    theta: q_4
    a: 0
    d: 0.17415
    alpa: 90
  joint5:
    theta: q_5
    a: 0
    d: 0.11985
    alpa: -90
  joint6:
    theta: q_6
    a: 0
    d: 0.11655
    alpa: 0